#!/bin/bash
####################################################################
# SKULL Framework - by Tomas Pollak (github.com/tomas)
# (c) 2010 - Fork Ltd
# License: GPLv3
####################################################################

skull_path="${BASH_SOURCE[0]%/*}"
[ -f "$skull_path" ] && skull_path=$(dirname "$skull_path")
PATH=/bin:/sbin:/usr/bin:/usr/sbin:$PATH

####################################################################
# bash behaviour
####################################################################

# set +e
set +bm
shopt -s expand_aliases
shopt -s extglob

####################################################################
# base requires
####################################################################

source "${skull_path}/base/loader.sh"

load "${skull_path}/base/function.sh"
load "${skull_path}/base/logger.sh"
load "${skull_path}/base/env.sh" && Env.set
load "${skull_path}/base/class.sh"
load "${skull_path}/base/system"

####################################################################
# libs and utils
####################################################################

load "${skull_path}/lib/*.sh"
load "${skull_path}/util/*.sh"
load "${skull_path}/plugins/*"

####################################################################
# initialization
####################################################################

# init_classes Array Dir File Hash Numeric Process String XmlNode
init_classes Array Hash File Numeric String

debug "Skull framework ready!"
